[package]
name = "prusti-polyfill"
version = "0.1.0"
authors = ["Parker Lawrence <liverspleenkidney@gmail.com>"]
edition = "2018"

[dependencies]
syn = "1.0"
quote = "1.0"

[lib]
proc-macro = true



